services:
  database:
    image: mysql:8.0
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: taskflow
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
