spring:
  application:
    name: TaskFlowApi
  datasource:
    url: jdbc:mysql://localhost:3306/taskflow
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
server:
  port: 9000
